name: build-test-deloy-environment

# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
  workflow_dispatch:

env:
  #set
  NODE_VERSION: '18.x'


#Use a matrix strategy to use Node.js versions 16.x and 18.x
jobs:
  install-build-test:

    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository.
      - name: Check out the repository
        uses: actions/checkout@v3

      # Set up a Node.js environment using the specified node version.
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: 'npm'
      - name: Install, Build, Test
        run: |
          npm ci
          npm run build --if-present
          npm test

  stage_deploy:
    runs-on: ubuntu-latest
    needs: install-build-test
    environment:
      name: staging
        
    steps:
      - name: Deploy to staging
        run: |
          echo  "Deployed to staging environment"
          
  production_deploy:
    runs-on: ubuntu-latest
    needs: stage_deploy
    environment:
      name: production

      steps:
        - name: Deploy to production
          run: |
            echo  "Deployed to production environment"